name: Transform TXT to JSON

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  transform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install fs-extra
      
    - name: Create transform script
      run: |
        cat > transform.js << 'EOF'
        const fs = require('fs-extra');
        const path = require('path');

        async function processFiles() {
          try {
            const dataDir = path.join(process.cwd(), 'data');
            const resultDir = path.join(process.cwd(), 'result');
            
            // Create result directory if it doesn't exist
            await fs.ensureDir(resultDir);
            
            // Get all txt files in data directory
            const files = (await fs.readdir(dataDir)).filter(file => file.endsWith('.txt'));
            
            for (const file of files) {
              const filePath = path.join(dataDir, file);
              const content = await fs.readFile(filePath, 'utf8');
              
              // Process content into chapters
              const chapters = [];
              let currentChapter = null;
              
              const lines = content.split('\n');
              for (const line of lines) {
                if (line.match(/^chapter\s+\d+/i)) {
                  if (currentChapter) {
                    chapters.push(currentChapter);
                  }
                  currentChapter = {
                    title: line.trim(),
                    content: []
                  };
                } else if (currentChapter) {
                  if (line.trim() || currentChapter.content.length > 0) {
                    currentChapter.content.push(line);
                  }
                }
              }
              
              // Add the last chapter if it exists
              if (currentChapter) {
                chapters.push(currentChapter);
              }
              
              // Convert content arrays to strings
              chapters.forEach(chapter => {
                chapter.content = chapter.content.join('\n').trim();
              });
              
              // Write JSON file
              const outputFile = path.join(resultDir, `${path.basename(file, '.txt')}.json`);
              await fs.writeJson(outputFile, { chapters }, { spaces: 2 });
              console.log(`Processed ${file} -> ${path.basename(outputFile)}`);
            }
            
            console.log('All files processed successfully!');
          } catch (error) {
            console.error('Error processing files:', error);
            process.exit(1);
          }
        }

        processFiles();
        EOF
        
    - name: Run transform script
      run: node transform.js
      
    - name: Commit and push results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add result/
        git commit -m "Automated: Transform TXT files to JSON" || echo "No changes to commit"
        git push
